theme: minima
title: Why is there a man in my basement
author: GitHub User
email: Helpimscared@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Oh no he is climbing the stairs this is my last cry for help

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
